# Generated by Django 5.2.16 on 2026-07-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_assetcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_tag", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("purchase_date", models.DateField()),
                ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=150)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Damaged", "Damaged"),
                        ],
                        default="Excellent",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Allocated", "Allocated"),
                            ("Reserved", "Reserved"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Lost", "Lost"),
                            ("Retired", "Retired"),
                            ("Disposed", "Disposed"),
                        ],
                        default="Available",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="assets/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assetcategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
        ),
    ]
