# Generated by Django 5.2.16 on 2026-07-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="name",
            new_name="asset_name",
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="current_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="model_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Allocated", "Allocated"),
                    ("Maintenance", "Maintenance"),
                    ("Lost", "Lost"),
                    ("Disposed", "Disposed"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
