# Generated by Django 5.2.16 on 2026-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_rename_name_asset_asset_name_asset_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
