# Generated by Django 5.2.16 on 2026-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_assetallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetallocation",
            name="condition_check",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assetallocation",
            name="return_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assetallocation",
            name="return_requested",
            field=models.BooleanField(default=False),
        ),
    ]
