# Generated by Django 5.2.16 on 2026-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("Asset Summary", "Asset Summary"),
                            ("Department Summary", "Department Summary"),
                            ("Maintenance Summary", "Maintenance Summary"),
                            ("Allocation Summary", "Allocation Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
